In [7]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior_1.csv')

In [34]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,NaN
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young adult,NaN
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [36]:
df.describe(include = 'all')

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3361.000000
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,NaN,6,7,4,NaN
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,NaN,PayPal,Every 3 Months,Young adult,NaN
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,NaN,677,584,1028,NaN
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750051,NaN,NaN,NaN,25.351538,NaN,NaN,NaN,102.304671
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.713590,NaN,NaN,NaN,14.447125,NaN,NaN,NaN,123.236962
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,14.000000
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,13.000000,NaN,NaN,NaN,14.000000
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,90.000000
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,90.000000
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,365.000000

In [11]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [12]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [13]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [14]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [16]:
df=df.rename(columns = {'purchase_amount_(usd)':'purchase_amount'})

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
# create a column age_group
labels = ['Young adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [19]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young adult
2   50  Middle-aged
3   21  Young adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young adult
8   26  Young adult
9   57  Middle-aged

In [20]:
# create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly' : 14,
    'Weeky': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [21]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      NaN                 Weekly
3                      NaN                 Weekly
4                    365.0               Annually
5                      NaN                 Weekly
6                     90.0              Quarterly
7                      NaN                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [22]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [23]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [24]:
df = df.drop('promo_code_used', axis = 1)

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [26]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binaryNote: you may need to restart the kernel to use updated packages.

  Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\user\downloads\anaconda\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\downloads\anaconda\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\downloads\anaconda\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.8 MB 5.7 MB/s eta 0:00:01
   ---- ----------------------------------- 0.3/2.8 MB 4.8 MB/s eta 0:00:01
   ----- ---------------------------------- 0.4/2.8 MB 3.5 MB/s eta 0:00:01
   ----- ---------------------------------- 0.4/2.8 MB 3.5 MB/s eta 0:00:01
   ----- ---------------------------------- 0.4/2.8 MB 3.5 MB/s eta 0:00:01
   ------- -------------------------------- 0.5/2.8 MB 1.7 MB/s eta 0:00:02
   --------- ------------------------------ 0.6/2.8 MB 1.9 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.8 MB 1.9 MB/s eta 0:00:02
   ------------ --------------------------- 0.9/2.8 MB 2.1 MB/s eta 0:00:01
   -------------- ------------------------- 1.0/2.8 MB 2.1 MB/s eta 0:00:01
   --------------- ------------------------ 1.1/2.8 MB 2.0 MB/s eta 0:00:01
   ----------------- ---------------------- 1.2/2.8 MB 2.1 MB/s eta 0:00:01
   -------------------- ------------------- 1.4/2.8 MB 2.1 MB/s eta 0:00:01
   ----------------------- ---------------- 1.6/2.8 MB 2.3 MB/s eta 0:00:01
   ----------------------- ---------------- 1.6/2.8 MB 2.3 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------- ----------- 2.0/2.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 2.5 MB/s eta 0:00:01
   -------------------------------- ------- 2.2/2.8 MB 2.2 MB/s eta 0:00:01
   --------------------------------- ------ 2.3/2.8 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 2.5/2.8 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  2.7/2.8 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 2.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [30]:
from sqlalchemy import create_engine
#step1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"    # default user
password = "7596"    # the password you set during installation
host = "localhost"    # if running locally
port = "5432"      # default Postgre port
database = "customer_behavior"   # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# step2: LOad dataframe into PostgreSQL 
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists = "replace", index = False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.